### PR TITLE
Add go-ethereum examples directory

### PR DESCRIPTION
**Pull request by sukanyaparashar**
This PR adds a go-ethereum examples directory which includes some smart contracts deployment examples using Go with go-ethereum SDK.

### CODE REVIEW

**Comment by mnedelchev-vn** [comment]
@sukanyaparashar Very nice tutorial, but let's change few things:
1. It's kinda bad that we ask users to copy the project from neon-hardhat to new folder GoProjects. Isn't it best to create the `src`, `pkg` and `bin` folders inside neon-tutorials/go-ethereum and to move the current neon-tutorials/go-ethereum content inside neon-tutorials/go-ethereum/src. This way we skip the step where they're copying anything.
2. Steps 4. and 5. in the readme are unclear. Add to step 4. that they have run command `nano ~/.zshrc` for Macs and `nano ~/. bash_profile ` for Linux. Add also a note that they can get the full path of GoProjects with `pwd` command.
3. Change the commands in step 5. to `source ~/.zshrc` for Macs and `source ~/. bash_profile ` for Linux.
4. If you want to keep both **Interact with the Storage smart contract** and **Interact with the TestERC20 smart contract** examples separate them in different .go files.

**Comment by sukanyaparashar** [comment]
> @sukanyaparashar Very nice tutorial, but let's change few things:
> 
> 1. It's kinda bad that we ask users to copy the project from neon-hardhat to new folder GoProjects. Isn't it best to create the `src`, `pkg` and `bin` folders inside neon-tutorials/go-ethereum and to move the current neon-tutorials/go-ethereum content inside neon-tutorials/go-ethereum/src. This way we skip the step where they're copying anything.

For this point, there are some complexities in creating `src`, `pkg` and `bin` folders inside this repository. Because, developing with Go will be a native app development and not a framework. For native Go development, the best way is to have the GOPATH set outside separately and it will already be in the user's machine if the user is familiar with Golang and already have a set GOPATH. And also it is not preferable to set the GOPATH inside of this repository as it should be somewhere independent of the `neon-tutorials` repository to be able to hold other Go applications inside of it.

There are 2 ways we can approach this -
1. Cloning this repository inside GOPATH's `src` directory, but I have tried it that way and it all messes up with the imports and is not possible to resolve in that way. The imports seems to be all broken inside the `neon-tutorials`because the directory under which we have the `go.mod` file should be the root directory for the imports to work. In this case, we have the directory `neon-tutorials/go-ethereum` which makes all the imports break.

2. Another approach is that we can completely separate the go-ethereum SDK to another repository. This will work when we clone the repository in the `src` directory of GOPATH directly.

**Comment by sukanyaparashar** [comment]
> 2. Steps 4. and 5. in the readme are unclear. Add to step 4. that they have run command `nano ~/.zshrc` for Macs and `nano ~/. bash_profile ` for Linux. Add also a note that they can get the full path of GoProjects with `pwd` command.
> 3. Change the commands in step 5. to `source ~/.zshrc` for Macs and `source ~/. bash_profile ` for Linux.
> 4. If you want to keep both **Interact with the Storage smart contract** and **Interact with the TestERC20 smart contract** examples separate them in different .go files.

I will implement these recommendations after we resolve the previous point.

**Comment by mnedelchev-vn** [comment]
> > @sukanyaparashar Very nice tutorial, but let's change few things:
> > 
> > 1. It's kinda bad that we ask users to copy the project from neon-hardhat to new folder GoProjects. Isn't it best to create the `src`, `pkg` and `bin` folders inside neon-tutorials/go-ethereum and to move the current neon-tutorials/go-ethereum content inside neon-tutorials/go-ethereum/src. This way we skip the step where they're copying anything.
> 
> For this point, there are some complexities in creating `src`, `pkg` and `bin` folders inside this repository. Because, developing with Go will be a native app development and not a framework. For native Go development, the best way is to have the GOPATH set outside separately and it will already be in the user's machine if the user is familiar with Golang and already have a set GOPATH. And also it is not preferable to set the GOPATH inside of this repository as it should be somewhere independent of the `neon-tutorials` repository to be able to hold other Go applications inside of it.
> 
> There are 2 ways we can approach this -
> 
> 1. Cloning this repository inside GOPATH's `src` directory, but I have tried it that way and it all messes up with the imports and is not possible to resolve in that way. The imports seems to be all broken inside the `neon-tutorials`because the directory under which we have the `go.mod` file should be the root directory for the imports to work. In this case, we have the directory `neon-tutorials/go-ethereum` which makes all the imports break.
> 2. Another approach is that we can completely separate the go-ethereum SDK to another repository. This will work when we clone the repository in the `src` directory of GOPATH directly.

You have a point, I think 2. is the best solution that we can take for now. But still the repo with the go-ethereum example can be included in the main readme of neon-tutorials. Let's proceed with 2.?

**Comment by sukanyaparashar** [comment]
> > > @sukanyaparashar Very nice tutorial, but let's change few things:
> > > 
> > > 1. It's kinda bad that we ask users to copy the project from neon-hardhat to new folder GoProjects. Isn't it best to create the `src`, `pkg` and `bin` folders inside neon-tutorials/go-ethereum and to move the current neon-tutorials/go-ethereum content inside neon-tutorials/go-ethereum/src. This way we skip the step where they're copying anything.
> > 
> > 
> > For this point, there are some complexities in creating `src`, `pkg` and `bin` folders inside this repository. Because, developing with Go will be a native app development and not a framework. For native Go development, the best way is to have the GOPATH set outside separately and it will already be in the user's machine if the user is familiar with Golang and already have a set GOPATH. And also it is not preferable to set the GOPATH inside of this repository as it should be somewhere independent of the `neon-tutorials` repository to be able to hold other Go applications inside of it.
> > There are 2 ways we can approach this -
> > 
> > 1. Cloning this repository inside GOPATH's `src` directory, but I have tried it that way and it all messes up with the imports and is not possible to resolve in that way. The imports seems to be all broken inside the `neon-tutorials`because the directory under which we have the `go.mod` file should be the root directory for the imports to work. In this case, we have the directory `neon-tutorials/go-ethereum` which makes all the imports break.
> > 2. Another approach is that we can completely separate the go-ethereum SDK to another repository. This will work when we clone the repository in the `src` directory of GOPATH directly.
> 
> You have a point, I think 2. is the best solution that we can take for now. But still the repo with the go-ethereum example can be included in the main readme of neon-tutorials as a link. Let's proceed with 2.?

I think this will be the best way to move forward for the Go native dApps. Yes, I can link the repository in the neon-tutorials README for reference. 

Then, I will close this PR and open the new repository and and move our discussion there. I will move the contents as it is from here and make a new PR with the changes you mentioned in that repository. Is that fine?

**Comment by sukanyaparashar** [comment]
> 4. If you want to keep both **Interact with the Storage smart contract** and **Interact with the TestERC20 smart contract** examples separate them in different .go files.

@mnedelchev-vn , For this point, Go packages can contain only one `main` function which is considered to be executable and the entry point. So, the functions can't be separated into 2 different `.go` files.

**Pull request closed without merging**
